# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70e9b6a13b52742dac40c9b44cc40960fe2277f72ca065ca203272d0cd44055023934c46d74cd7b528f777598ade3a7386e0b272b1e5280d215eee08f0cb33ae

test:
  secret_key_base: d4733d34e150bd5a34c8553107e3bd389d891a362f86d200ce0f708c73b421260dd9adc2c9e55ba78a172794a791a3b791ade06e57e6a98e66dbefd2e0f72d07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
